<?php
/**
 * config/textos_evento.php
 * Textos específicos por tipo de evento para las plantillas de tarjetas.
 * Uso: $txt = textos_para_evento($tarjeta['nombre_evento']);
 */

$_textos_por_evento = [

    'boda' => [
        'agasajados'            => 'los novios',
        'agasajado_singular'    => 'los novios',
        'titulo_rsvp'           => 'Confirmá tu Asistencia',
        'subtitulo_rsvp'        => 'Tu respuesta nos ayuda a organizar mejor este día tan especial.',
        'muro_pregunta'         => '¿Querés dejarles un mensaje a los novios?',
        'muro_titulo'           => 'Muro de Deseos',
        'muro_placeholder'      => 'Escribiles un deseo, una frase o una anécdota...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Regalos',
        'msg_regalos_defecto'   => 'Tu presencia es nuestro mejor regalo. Si deseás ayudarnos con nuestra luna de miel, podés hacerlo aquí:',
        'titulo_calendario'     => 'Agendá la boda',
        'titulo_galeria'        => 'Galería Colaborativa',
        'texto_galeria'         => '¡Queremos ver este día a través de tus ojos! Sumá tus fotos y compartí el recuerdo.',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos!',
        'dias'                  => 'Días',
        'horas'                 => 'Horas',
        'minutos'               => 'Minutos',
        'segundos'              => 'Segundos',
        'titulo_playlist'       => 'Playlist de la Boda',
        'subtitulo_playlist'    => '¡Ayudanos a armar la fiesta! Sugerí la canción que no puede faltar.',
        'titulo_confirmacion'   => 'Confirmá tu Asistencia',
        'texto_confirmacion'    => 'Por favor confirmá tu presencia para que podamos organizar todo de la mejor manera.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        // Boda: dos momentos
        'tiene_dos_momentos'    => true,
        'momento1_label'        => 'Ceremonia',
        'momento2_label'        => 'Celebración / Fiesta',
    ],

    'cumpleaños' => [
        'agasajados'            => 'el/la festejado/a',
        'agasajado_singular'    => 'el/la festejado/a',
        'titulo_rsvp'           => 'Confirmá tu Asistencia',
        'subtitulo_rsvp'        => 'Tu respuesta nos ayuda a organizar la fiesta.',
        'muro_pregunta'         => '¿Querés dejarle un mensaje al/a la festejado/a?',
        'muro_titulo'           => 'Muro de Mensajes',
        'muro_placeholder'      => 'Escribile un saludo o una anécdota...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Regalos',
        'msg_regalos_defecto'   => 'Tu presencia es el mejor regalo. Si querés ayudarlo/a, podés hacerlo aquí:',
        'titulo_calendario'     => 'Agendá el cumpleaños',
        'titulo_galeria'        => 'Galería Colaborativa',
        'texto_galeria'         => '¡Compartí tus fotos de la fiesta!',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos!',
        'dias' => 'Días', 'horas' => 'Horas', 'minutos' => 'Minutos', 'segundos' => 'Segundos',
        'titulo_playlist'       => 'Playlist de la Fiesta',
        'subtitulo_playlist'    => '¡Sugerí la canción que no puede faltar!',
        'titulo_confirmacion'   => 'Confirmá tu Asistencia',
        'texto_confirmacion'    => 'Confirmá tu presencia para que podamos organizar todo.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        'tiene_dos_momentos'    => false,
    ],

    '15 años' => [
        'agasajados'            => 'la quinceañera',
        'agasajado_singular'    => 'la quinceañera',
        'titulo_rsvp'           => 'Confirmá tu Asistencia',
        'subtitulo_rsvp'        => 'Tu respuesta nos ayuda a organizar esta noche tan especial.',
        'muro_pregunta'         => '¿Querés dejarle un mensaje a la quinceañera?',
        'muro_titulo'           => 'Mensajes para la Quinceañera',
        'muro_placeholder'      => 'Escribile un deseo o un consejo para esta nueva etapa...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Regalos',
        'msg_regalos_defecto'   => 'Tu presencia es el mejor regalo. Si querés sorprenderla, podés hacerlo aquí:',
        'titulo_calendario'     => 'Agendá los 15 años',
        'titulo_galeria'        => 'Galería Colaborativa',
        'texto_galeria'         => '¡Compartí tus fotos de esta noche mágica!',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos para su gran noche!',
        'dias' => 'Días', 'horas' => 'Horas', 'minutos' => 'Minutos', 'segundos' => 'Segundos',
        'titulo_playlist'       => 'Playlist de los 15',
        'subtitulo_playlist'    => '¡Sugerí la canción que no puede faltar en su noche!',
        'titulo_confirmacion'   => 'Confirmá tu Asistencia',
        'texto_confirmacion'    => 'Confirmá tu presencia para ayudarnos a organizar esta noche especial.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        'tiene_dos_momentos'    => false,
    ],

    'bautismo' => [
        'agasajados'            => 'el/la bautizadx',
        'agasajado_singular'    => 'el/la bautizadx',
        'titulo_rsvp'           => 'Confirmá tu Asistencia',
        'subtitulo_rsvp'        => 'Tu respuesta nos ayuda a organizar este día especial.',
        'muro_pregunta'         => '¿Querés dejarle un mensaje al/a la bautizadx?',
        'muro_titulo'           => 'Mensajes y Deseos',
        'muro_placeholder'      => 'Escribile un deseo para este nuevo comienzo...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Regalos',
        'msg_regalos_defecto'   => 'Tu presencia y cariño es el mejor regalo.',
        'titulo_calendario'     => 'Agendá el bautismo',
        'titulo_galeria'        => 'Galería Colaborativa',
        'texto_galeria'         => '¡Compartí tus fotos de este día tan especial!',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos!',
        'dias' => 'Días', 'horas' => 'Horas', 'minutos' => 'Minutos', 'segundos' => 'Segundos',
        'titulo_playlist'       => 'Música del Festejo',
        'subtitulo_playlist'    => '¡Sugerí la canción que no puede faltar!',
        'titulo_confirmacion'   => 'Confirmá tu Asistencia',
        'texto_confirmacion'    => 'Confirmá tu presencia para ayudarnos a organizar el festejo.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        'tiene_dos_momentos'    => false,
    ],

    'egreso' => [
        'agasajados'            => 'los egresados',
        'agasajado_singular'    => 'los egresados',
        'titulo_rsvp'           => 'Confirmá tu Asistencia',
        'subtitulo_rsvp'        => 'Tu respuesta nos ayuda a organizar esta noche épica.',
        'muro_pregunta'         => '¿Querés dejarles un mensaje a los egresados?',
        'muro_titulo'           => 'Mensajes para los Egresados',
        'muro_placeholder'      => 'Escribiles un deseo o un recuerdo de esta etapa...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Regalos',
        'msg_regalos_defecto'   => 'Tu presencia es lo que más importa. Si querés sumar algo más, podés hacerlo aquí:',
        'titulo_calendario'     => 'Agendá el egreso',
        'titulo_galeria'        => 'Galería Colaborativa',
        'texto_galeria'         => '¡Compartí tus fotos de esta noche que no se olvida!',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos para la gran noche!',
        'dias' => 'Días', 'horas' => 'Horas', 'minutos' => 'Minutos', 'segundos' => 'Segundos',
        'titulo_playlist'       => 'Playlist del Egreso',
        'subtitulo_playlist'    => '¡Sugerí la canción que tiene que sonar esta noche!',
        'titulo_confirmacion'   => 'Confirmá tu Asistencia',
        'texto_confirmacion'    => 'Confirmá tu presencia para ayudarnos a organizar todo.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        'tiene_dos_momentos'    => false,
    ],

    'baby shower' => [
        'agasajados'            => 'la futura mamá',
        'agasajado_singular'    => 'la futura mamá',
        'titulo_rsvp'           => 'Confirmá tu Asistencia',
        'subtitulo_rsvp'        => 'Tu respuesta nos ayuda a preparar todo con amor.',
        'muro_pregunta'         => '¿Querés dejarle un mensaje a la futura mamá?',
        'muro_titulo'           => 'Mensajes para la Futura Mamá',
        'muro_placeholder'      => 'Escribile un deseo o un consejo para esta hermosa etapa...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Lista de Regalos',
        'msg_regalos_defecto'   => 'Si querés regalarle algo especial al bebé, podés ayudar aquí:',
        'titulo_calendario'     => 'Agendá el Baby Shower',
        'titulo_galeria'        => 'Galería Colaborativa',
        'texto_galeria'         => '¡Compartí tus fotos de este día tan dulce!',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos para este momento especial!',
        'dias' => 'Días', 'horas' => 'Horas', 'minutos' => 'Minutos', 'segundos' => 'Segundos',
        'titulo_playlist'       => 'Música del Baby Shower',
        'subtitulo_playlist'    => '¡Sugerí la canción para ambientar este día!',
        'titulo_confirmacion'   => 'Confirmá tu Asistencia',
        'texto_confirmacion'    => 'Confirmá tu presencia para ayudarnos a preparar todo.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        'tiene_dos_momentos'    => false,
    ],

    'revelación de género' => [
        'agasajados'            => 'los futuros papás',
        'agasajado_singular'    => 'los futuros papás',
        'titulo_rsvp'           => 'Confirmá tu Asistencia',
        'subtitulo_rsvp'        => 'Tu respuesta nos ayuda a organizar este momento mágico.',
        'muro_pregunta'         => '¿Cuál es tu predicción? ¿Nena o nene? ¡Dejá tu mensaje!',
        'muro_titulo'           => '¿Nena o Nene?',
        'muro_placeholder'      => 'Dejá tu predicción y un mensaje para los futuros papás...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Regalos',
        'msg_regalos_defecto'   => 'Tu presencia es el mejor regalo. Si querés sumar algo más, podés hacerlo aquí:',
        'titulo_calendario'     => 'Agendá la Revelación',
        'titulo_galeria'        => 'Galería Colaborativa',
        'texto_galeria'         => '¡Compartí tus fotos de este momento único!',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos para descubrir el secreto!',
        'dias' => 'Días', 'horas' => 'Horas', 'minutos' => 'Minutos', 'segundos' => 'Segundos',
        'titulo_playlist'       => 'Música del Evento',
        'subtitulo_playlist'    => '¡Sugerí la canción para ambientar la revelación!',
        'titulo_confirmacion'   => 'Confirmá tu Asistencia',
        'texto_confirmacion'    => 'Confirmá tu presencia para ayudarnos a organizar todo.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        'tiene_dos_momentos'    => false,
    ],

    'comunión' => [
        'agasajados'            => 'el/la comulgante',
        'agasajado_singular'    => 'el/la comulgante',
        'titulo_rsvp'           => 'Confirmá tu Asistencia',
        'subtitulo_rsvp'        => 'Tu respuesta nos ayuda a organizar este día de fe.',
        'muro_pregunta'         => '¿Querés dejarle un mensaje al/a la comulgante?',
        'muro_titulo'           => 'Mensajes y Bendiciones',
        'muro_placeholder'      => 'Escribile una bendición o un deseo para este día especial...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Regalos',
        'msg_regalos_defecto'   => 'Tu presencia y cariño es lo más valioso.',
        'titulo_calendario'     => 'Agendá la Comunión',
        'titulo_galeria'        => 'Galería Colaborativa',
        'texto_galeria'         => '¡Compartí tus fotos de este día lleno de fe!',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos para este día tan especial!',
        'dias' => 'Días', 'horas' => 'Horas', 'minutos' => 'Minutos', 'segundos' => 'Segundos',
        'titulo_playlist'       => 'Música del Festejo',
        'subtitulo_playlist'    => '¡Sugerí la canción para el festejo!',
        'titulo_confirmacion'   => 'Confirmá tu Asistencia',
        'texto_confirmacion'    => 'Confirmá tu presencia para ayudarnos a organizar el festejo.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        'tiene_dos_momentos'    => false,
    ],

    'confirmación' => [
        'agasajados'            => 'el/la confirmandx',
        'agasajado_singular'    => 'el/la confirmandx',
        'titulo_rsvp'           => 'Confirmá tu Asistencia',
        'subtitulo_rsvp'        => 'Tu respuesta nos ayuda a organizar este día especial.',
        'muro_pregunta'         => '¿Querés dejarle un mensaje al/a la confirmandx?',
        'muro_titulo'           => 'Mensajes y Deseos',
        'muro_placeholder'      => 'Escribile un deseo o una bendición...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Regalos',
        'msg_regalos_defecto'   => 'Tu presencia y cariño es lo más valioso.',
        'titulo_calendario'     => 'Agendá la Confirmación',
        'titulo_galeria'        => 'Galería Colaborativa',
        'texto_galeria'         => '¡Compartí tus fotos de este día de fe!',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos!',
        'dias' => 'Días', 'horas' => 'Horas', 'minutos' => 'Minutos', 'segundos' => 'Segundos',
        'titulo_playlist'       => 'Música del Festejo',
        'subtitulo_playlist'    => '¡Sugerí la canción para el festejo!',
        'titulo_confirmacion'   => 'Confirmá tu Asistencia',
        'texto_confirmacion'    => 'Confirmá tu presencia para ayudarnos a organizar el festejo.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        'tiene_dos_momentos'    => false,
    ],

    'aniversario' => [
        'agasajados'            => 'la pareja',
        'agasajado_singular'    => 'la pareja',
        'titulo_rsvp'           => 'Confirmá tu Asistencia',
        'subtitulo_rsvp'        => 'Tu presencia hace más especial este festejo.',
        'muro_pregunta'         => '¿Querés dejarles un mensaje a los festejantes?',
        'muro_titulo'           => 'Mensajes para la Pareja',
        'muro_placeholder'      => 'Escribiles un deseo o una anécdota compartida...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Regalos',
        'msg_regalos_defecto'   => 'Tu presencia es el mejor regalo. Si querés sumar algo más, podés hacerlo aquí:',
        'titulo_calendario'     => 'Agendá el Aniversario',
        'titulo_galeria'        => 'Galería Colaborativa',
        'texto_galeria'         => '¡Compartí tus fotos de este festejo!',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos para celebrar!',
        'dias' => 'Días', 'horas' => 'Horas', 'minutos' => 'Minutos', 'segundos' => 'Segundos',
        'titulo_playlist'       => 'Playlist del Aniversario',
        'subtitulo_playlist'    => '¡Sugerí la canción que no puede faltar!',
        'titulo_confirmacion'   => 'Confirmá tu Asistencia',
        'texto_confirmacion'    => 'Confirmá tu presencia para ayudarnos a organizar todo.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        'tiene_dos_momentos'    => false,
    ],

    'corporativo' => [
        'agasajados'            => 'el equipo',
        'agasajado_singular'    => 'el equipo',
        'titulo_rsvp'           => 'Confirmá tu Asistencia',
        'subtitulo_rsvp'        => 'Tu confirmación nos ayuda a organizar el evento.',
        'muro_pregunta'         => '¿Querés dejar un comentario sobre el evento?',
        'muro_titulo'           => 'Comentarios',
        'muro_placeholder'      => 'Dejá tu comentario o pregunta...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Información adicional',
        'msg_regalos_defecto'   => 'Para consultas sobre el evento, contactate con los organizadores.',
        'titulo_calendario'     => 'Agendar el Evento',
        'titulo_galeria'        => 'Galería del Evento',
        'texto_galeria'         => '¡Compartí tus fotos del evento!',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos para el evento!',
        'dias' => 'Días', 'horas' => 'Horas', 'minutos' => 'Minutos', 'segundos' => 'Segundos',
        'titulo_playlist'       => 'Playlist del Evento',
        'subtitulo_playlist'    => '¡Sugerí música para el evento!',
        'titulo_confirmacion'   => 'Confirmá tu Asistencia',
        'texto_confirmacion'    => 'Por favor confirmá tu asistencia para organizar mejor el evento.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        'tiene_dos_momentos'    => false,
    ],

    'deportivo' => [
        'agasajados'            => 'los deportistas',
        'agasajado_singular'    => 'los deportistas',
        'titulo_rsvp'           => 'Confirmá tu Participación',
        'subtitulo_rsvp'        => 'Tu confirmación nos ayuda a organizar el evento deportivo.',
        'muro_pregunta'         => '¿Querés dejar un mensaje para el evento?',
        'muro_titulo'           => 'Mensajes del Evento',
        'muro_placeholder'      => 'Dejá un mensaje de aliento o un comentario...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Información adicional',
        'msg_regalos_defecto'   => 'Para más información sobre el evento, contactate con los organizadores.',
        'titulo_calendario'     => 'Agendar el Evento',
        'titulo_galeria'        => 'Galería del Evento',
        'texto_galeria'         => '¡Compartí tus fotos del evento deportivo!',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos para el evento!',
        'dias' => 'Días', 'horas' => 'Horas', 'minutos' => 'Minutos', 'segundos' => 'Segundos',
        'titulo_playlist'       => 'Música del Evento',
        'subtitulo_playlist'    => '¡Sugerí música para el evento!',
        'titulo_confirmacion'   => 'Confirmá tu Participación',
        'texto_confirmacion'    => 'Confirmá tu participación para organizar mejor el evento.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        'tiene_dos_momentos'    => false,
    ],

    // Eventos con textos genéricos (jubilación, inauguración, despedida, reunión familia)
    '_default' => [
        'agasajados'            => 'los agasajados',
        'agasajado_singular'    => 'el/la agasajado/a',
        'titulo_rsvp'           => 'Confirmá tu Asistencia',
        'subtitulo_rsvp'        => 'Tu respuesta nos ayuda a organizar mejor el evento.',
        'muro_pregunta'         => '¿Querés dejarles un mensaje a los agasajados?',
        'muro_titulo'           => 'Muro de Mensajes',
        'muro_placeholder'      => 'Escribí tu mensaje...',
        'titulo_ubicacion'      => '¿Cómo llegar?',
        'titulo_regalos'        => 'Regalos',
        'msg_regalos_defecto'   => 'Tu presencia es el mejor regalo.',
        'titulo_calendario'     => 'Agendá el Evento',
        'titulo_galeria'        => 'Galería Colaborativa',
        'texto_galeria'         => '¡Compartí tus fotos del evento!',
        'btn_galeria'           => 'Ver y subir fotos',
        'faltan'                => '¡Falta cada vez menos!',
        'dias' => 'Días', 'horas' => 'Horas', 'minutos' => 'Minutos', 'segundos' => 'Segundos',
        'titulo_playlist'       => 'Playlist del Evento',
        'subtitulo_playlist'    => '¡Sugerí la canción que no puede faltar!',
        'titulo_confirmacion'   => 'Confirmá tu Asistencia',
        'texto_confirmacion'    => 'Por favor confirmá tu presencia para que podamos organizar todo.',
        'btn_whatsapp'          => 'Confirmar por WhatsApp',
        'tiene_dos_momentos'    => false,
    ],
];

/**
 * Devuelve los textos para un tipo de evento dado.
 * Si no existe el tipo, usa los textos por defecto.
 */
function textos_para_evento(string $nombre_evento): array
{
    global $_textos_por_evento;
    $slug = mb_strtolower(trim($nombre_evento));
    return $_textos_por_evento[$slug] ?? $_textos_por_evento['_default'];
}